debug: false

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){blue} %clr(%level) %clr(%logger{36}){cyan} - %msg%n"
  level:
    root: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    org.hibernate.cfg.Configuration: TRACE
    org.hibernate.cfg.Environment: TRACE
    org.hibernate.cfg.Settings: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.cache: TRACE
    org.hibernate.SQL: DEBUG
    com.demo.keep: DEBUG

management:
  server:
    port: 8443

server:
  error:
    include-stacktrace: never
  servlet:
    session:
      persistent: false
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: localhost
    key-store-type: PKCS12
    key-alias: localhost
    protocol: TLSv1.2

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      idleTimeout: 60000
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        batch_size: 10
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        show_sql: false
        type: trace
        use_sql_comments: false
        jdbc.batch_size: 50
        jdbc.batch_versioned_data: true
  output:
    ansi:
      enabled: always
  profiles:
    active: dev,embedded,swagger

jwt:
  key: FB8D6591183B4AEA3E6975BBDFBD52FB99DD2E4BF565B634A1168C488E
